apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-cinder-retain
provisioner: cinder.csi.openstack.org
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  availability: nova
