apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-cinder-delete
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: cinder.csi.openstack.org
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  availability: nova
